# [keybinds]
# close = ["Escape"]
# next = ["down"]
# previous = ["up"]
# toggle_exact = ["ctrl e"]
# resume_last_query = ["ctrl r"]
# quick_activate = ["F1", "F2", "F3", "F4"]

theme = "default"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
left = ["Left"]
right = ["Right"]
down = ["Down"]
up = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = ["F1", "F2", "F3", "F4"]
page_down = ["Page_Down"]
page_up = ["Page_Up"]
show_actions = ["alt j"]
